### ISSUE TITLE
help and link to readthedocs are documzntation broken in readme.

### ISSUE THREAD

**Issue by Stephanevg** [jpsider/ReportCardPS#5]
Title is clear enough I think ;)

**Comment by jpsider** [comment]
True story! I've updated the links. However, they probably still are not super useful yet. I'm working on the actual module now. Hopefully I'll have a first pass soon.

**Comment by jpsider** [comment]
Docs are updated. Enjoy! 
https://reportcardps.readthedocs.io/en/latest/?badge=latest
